ALTER TABLE public.transactions 
  ADD COLUMN IF NOT EXISTS operacao TEXT,
  ADD COLUMN IF NOT EXISTS tipo_situacao TEXT,
  ADD COLUMN IF NOT EXISTS tipo_data TEXT,
  ADD COLUMN IF NOT EXISTS data_inicio DATE,
  ADD COLUMN IF NOT EXISTS data_final DATE,
  ADD COLUMN IF NOT EXISTS venda TEXT,
  ADD COLUMN IF NOT EXISTS fatura TEXT,
  ADD COLUMN IF NOT EXISTS duplicata TEXT,
  ADD COLUMN IF NOT EXISTS boleto TEXT,
  ADD COLUMN IF NOT EXISTS pessoa TEXT,
  ADD COLUMN IF NOT EXISTS codigo TEXT,
  ADD COLUMN IF NOT EXISTS cliente TEXT;
